### PR TITLE
Private asciicasts

### PR DESCRIPTION
**Pull request by sickill**

### CODE REVIEW

**Comment by diwu1989** [comment]
Any progress on this? we really need this

**Comment by KenjiHollis** [comment]
:+1: :+1: :+1: 

This would make our demos much more meaningful in front of crowds.  Please, please, please implement this.  I'd be happy to pay for this as a service!!

**Comment by logankoester** [comment]
Really looking forward to this one as well!

**Comment by mcoms** [comment]
:tada: :balloon: :+1:

**Comment by hh** [comment]
:happy:

**Pull request merged**
