### PR TITLE
iframe based embedding

### PR DESCRIPTION
**Pull request by sickill**
So far you could embed asciinema.org hosted recordings in your HTML pages by copy-pasting the `<script>` tag as described [here](https://asciinema.org/docs/embedding):

```html
<script type="text/javascript" src="https://asciinema.org/a/113463.js" id="asciicast-113463" async></script>
```

The existing embed script automatically inserts an `<iframe>` into a document, and resizes the iframe after the player inside initializes.

This PR adds direct iframe embedding support. Example:

```html
<iframe src="https://asciinema.org/a/113463/iframe"></iframe>
```

This allows for embedding in places where `<script>` tags are not allowed but `<iframe>` tags are.

There's major difference in how the sizing of the player works here though.
When creating the player here we ignore the width/height specified in the asciicast file (dimensions of the original terminal window at the time of recording). Instead, this version of iframe'd player adjust its size to the size of the visible part of the document in an iframe. This means you can control the size of the player by adjusting iframe's `width` and `height`. For example:

```html
<iframe src="https://asciinema.org/a/113463/iframe" style="width: 100%; height: 350px"></iframe>
```

Important gotcha here: when using the player size adjusted to the iframe, the size of the screen buffer of the internal virtual terminal emulator (in terms of columns/rows) is most likely different than user's terminal window at the time of recording. This can cause visual glitch for recordings where: a) "full screen" apps like `vim` were used (which use "secondary screen"), AND b) the iframe size is smaller than original terminal window size at the time of recording. In other words: if you iframe-embed recordings of non full screen terminal apps you'll most likely be fine, and if you embed anything with `vim/man/less/ncurses` then make sure the iframe on your page is big enough.

### CODE REVIEW

**Comment by coco98** [comment]
@sickill Is this not intended to work while embedding into sites?  This is the error I get:
```Refused to display 'https://asciinema.org/a/113463/iframe' in a frame because it set 'X-Frame-Options' to 'sameorigin'.```

**Comment by coco98** [comment]
I believe the fix would be something on the lines of:

```elixir
 |> put_resp_header("x-frame-options", "ALLOW-FROM " <> get_req_header(conn, "origin"))
```
at: https://github.com/asciinema/asciinema-server/blob/03614b16e4b81bc4108bc5f17661696c02c1d8d8/lib/asciinema_web/controllers/asciicast_controller.ex#L9

Ref: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options

Not sure if that's right. Just trying to help :)

**Comment by coco98** [comment]
I believe the fix would be something on the lines of:

```elixir
 |> put_resp_header("x-frame-options", "ALLOW-FROM " <> get_req_header(conn, "origin"))
```
at: https://github.com/asciinema/asciinema-server/blob/03614b16e4b81bc4108bc5f17661696c02c1d8d8/lib/asciinema_web/controllers/asciicast_controller.ex#L9

Ref: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options

Not sure if that's right. Just trying to help :)

**Comment by coco98** [comment]
I believe the fix would be something on the lines of:

```elixir
 |> put_resp_header("x-frame-options", "ALLOW-FROM " <> get_req_header(conn, "origin"))
```
at: https://github.com/asciinema/asciinema-server/blob/03614b16e4b81bc4108bc5f17661696c02c1d8d8/lib/asciinema_web/controllers/asciicast_controller.ex#L9

Ref: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options

Not sure if that's right. Just trying to help :)

**Comment by sickill** [comment]
@coco98 fixed in 5b238d8155e68134698d503259678ae2a44c487f, thanks!

**Comment by coco98** [comment]
Just tried it out and it works. 

However, the fullscreen/maximise button on the bottom right cornder doesn't work.

Here's the HTML you can try it out on:

```
<!doctype html>
<html>
<body>
    <iframe src="https://asciinema.org/a/113463/iframe"></iframe>
</body>
</html>
```

**Comment by coco98** [comment]
My bad. Allowing fullscreen on the iframe works:
```
<!doctype html>
<html>
<body>
    <iframe allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" src="https://asciinema.org/a/113463/iframe"></iframe>
</body>
</html>
```

However the terminal screen remains at the original height that the iframe had on the page it was embedded in.

**Comment by sickill** [comment]
@coco98 yes, entering fullscreen doesn't resize the terminal. That's not possible right now unfortunately. It's not a bug, but just something not supported.

**Pull request merged**
